### ISSUE TITLE
Cannot use a tsconfig.json with Rhum

### ISSUE THREAD

**Issue by ebebbington** [drashland/rhum#103]
## Summary

Unable to use a tsconfig with rhum, using the following lib options: `dom`, `deno.ns`

## Steps To Reproduce The Bug

1. Import rhum into a file
2. Create a ttsconfig with:
```
{
  "compilerOptions": {
    "lib": ["dom", "deno.ns"]
  }
}
```
3. Run file with config
4. See errors
5. Remove rhum dep
6. Run again
7. See no errors

## Expected Behavior

Should be able to use a tsconfig

## Suggested Solution(s)

Update std dependencies (master is updated, it just needs to be released)

**Comment by crookse** [comment]
closing. no longer needed.
