### ISSUE TITLE
How do I mock database calls in my endpoint

### ISSUE THREAD

**Issue by RogierdeRuijter** [drashland/rhum#118]
## Summary

I have the following method that is used for an endpoint. It looks something like this:

```typescript
export const endpointMethod: HandlerFunc = async (c: Context): Promise<any> => {
    const database = db.getDatebase("database");

    const collection = database.collection<Collection>("collection");

    const insertedEntry = await collection.insertOne({
      timestamp: new Date()
    });
};
```

What is the best way to mock the functions used here? Therefore, db.getDatebase(), database.collection(), and collection.insertOne(); From the [docs](https://drash.land/rhum/v1.x/#/tutorials/mocks) it seems like I can only mock the methods if I pass e.g. the `db` object to the endpointMethod, but this isn't really an option here since the endpoint can't take additional arguments. And that would but a bit ugly 😅

**Comment by crookse** [comment]
Hey @RogierdeRuijter! Sorry for the late response. I must've overlooked this in our Discord GitHub feed. Anyways, I think your only option might be to mock the entire `endpointMethod`.

I do have one question though. Where is `db` being defined? If `db` is defined outside of `endpointMethod`, then you might be able to use a combination of stubs and mocks to accomplish what you want.

**Comment by RogierdeRuijter** [comment]
Hee @crookse, thanks for your response!

Yes the database is defined in another file. This file looks something like this:

```typescript
import { MongoClient } from "https://deno.land/x/mongo@v0.22.0/mod.ts";

export class DB {
  public client: MongoClient;

  private dbName: string;
  private dbUsername: string;
  private dbPassword: string;
  private dbUrl: string;

  constructor() {
    this.dbName = Deno.env.get("DB_NAME") || "";
    this.dbUsername = Deno.env.get("DB_USERNAME") || "";
    this.dbPassword = Deno.env.get("DB_PASSWORD") || "";
    this.dbUrl = Deno.env.get("DB_URL") || "";
    this.client = {} as MongoClient;
  }

  async connect() {
    const client = new MongoClient();

    await client.connect({
      db: this.dbName,
      tls: true,
      servers: [
        {
          host: this.dbUrl,
          port: 27017,
        }
      ],
      credential: {
        username: this.dbUsername,
        password: this.dbPassword,
        db: this.dbName,
        mechanism: "SCRAM-SHA-1",
      },
    });

    this.client = client;
  }

  public getDatebase(databaseName: string) {
    return this.client.database(databaseName);
  }
}

const db = new DB();

export default db;
```

I was looking at the [stubs](https://drash.land/rhum/v1.x/#/tutorials/stubs) and [mocks](https://drash.land/rhum/v1.x/#/tutorials/mocks) documentation. And it doesn't seems to be the case that if I mock the `db` like this

```typescript
Rhum.testPlan("controller.ts", () => {
  Rhum.testSuite("endpointMethod()", () => {
    Rhum.testCase("it call the endpoint and return status code 200", () => {
      const mock = Rhum.mock(db).create();
      const result = endpointMethod();
      
     // This is simplified but you get the idea :D
      Rhum.asserts.assertEquals(result, 'status code: 200');
    });
  });
});

Rhum.run();
```

That the endpointMethod will use the mock. It seems to be that I have to pass it to the endpointMethod like this.

```typescript
const mock = Rhum.mock(db).create();
const result = endpointMethod(mock);
```
But I can't do this. Because I can't pass an additional parameter to the method since I use this method as a callback in a post request like this:

```typescript
import { Application } from "https://deno.land/x/abc/mod.ts";
import { endpointMethod } from "./controllers.ts";

const app = new Application();
app
  .post("/endpoint", endpointMethod)
  .start({ port: 3000 });
```
And if I could pass db here to the endpoint method I would prefer not to do this.

I am looking for something similar like how you can mock in Jest. For example, this:
```javascript
it('should return the product', async () => {
  const expectedProduct = {
    id: 1,
    name: 'football',
  };
  const productManager = new ProductManager();
  
  // This is the mocking part
  ----------------
  const mockGetById = jest.fn();
  ProductsClient.prototype.getById = mockGetById;
  mockGetById.mockReturnValue(Promise.resolve(expectedProduct));
  ----------------
  
   const result = await productManager.getProductToManage(1); 

  expect(result.name).toBe('football'); // It passes!
});

```
[source](https://dev.to/jackcaldwell/mocking-es6-class-methods-with-jest-bd7). Here you mock the `getById` function without passing the method ProductsClient to the getProductToManage. 

Is something like this possible?

**Comment by RogierdeRuijter** [comment]
I forgot to add this, but I want to the the `endpointMethod` so mocking the entire thing isn't really an option :)

**Comment by crookse** [comment]
@RogierdeRuijter, so i tried mocking the way you expect to mock and it looks like we need some extra functionality to support your use case. although im unsure what that functionality would look like -- i'd need to discuss this with the other team members

**Comment by crookse** [comment]
hey @RogierdeRuijter, firstly, apologies for a really late update on this. i'm not sure if you're still using rhum, but we released v2 and what you want to accomplish can be done through rhum's new `Fake()` test double and using import maps. while it may not be an elegant solution like jest's auto-mocking feature, it doesn't require anything other than rhum and an import map (which in my opinion can help keep the testing part of your codebase pretty lean). if you're still using rhum and still interested in the solution, it's in the zip file below:

[fake_database.zip](https://github.com/drashland/rhum/files/8500969/fake_database.zip)

if you have any questions about the setup, please feel free to reach out!

**Comment by crookse** [comment]
hi @RogierdeRuijter, closing this. feel free to re-open.
