### ISSUE TITLE
After hooks aren't ran if test case fails

### ISSUE THREAD

**Issue by ebebbington** [drashland/rhum#125]
***NOTE: Because we wrap the test case in a try/catch, if it errors, that assetion error is never actually thrown, we may need to save it and call it after the hooks***

## Summary

When using after hooks, and a test case fails, the after hooks are not executed

## Steps To Reproduce The Bug

1. Create a test plan and suite
2. Create a test case that throws an error
3. Create an afterAll hook that logs a message
4. Run test, the message from the hook wont be logged

## Expected Behavior

The after hooks should be ran because they are cleanup functions, they should be ran even if the test case fails

## Suggested Solution(s)

The hook attached fn in test_case.ts should do something like
```ts
// all the before hook logic as usual

let errorMsg = ""
try {
  await t.testCase()
} catch (_e) {
  errorMessage = _e.message
}
  
// after hooks logic as usual

// And because we caught any assertion errors, we need to throw them
if (errorMessage) {
  throw new AssertionError(errorMessage)
}

**Comment by crookse** [comment]
no longer need. v2 is in the pipeline and will only consist of test double logic
