### ISSUE TITLE
Mocked Class with Request param (Fetch Request Interface) throws TypeError for undefined method

### ISSUE THREAD

**Issue by rags2riches-prog** [drashland/rhum#131]
Given a Class that takes a [Request object](https://developer.mozilla.org/en-US/docs/Web/API/Request) as param :

```
export class Router {
  constructor() {}

  async handle(request: Request): Promise<string|Error> {
    const method = request.method.toLowerCase();
    const contentType = request.headers.get("Content-Type")

    if (method !== "post")
      throw TypeError(`Must use Post method only, found ${method} instead.\n\n`);

    if (contentType !== "application/json") 
      throw TypeError(`content-type must be application/json, found ${contentType} instead`);

    ......
```

 And a test...

```
Rhum.testCase("should validate request body with json schema validator", async () => {
      const req = new Request("http://localhost:8080", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(fakeData)
      })

      const router = Rhum.mock(Router).create()

      Rhum.asserts.assertEquals(router.calls.handle, 0)
      Rhum.asserts.assertEquals(await router.handle(req), true)
```

I get the following TypeError and I do not understand why:

```
TypeError: Cannot read properties of undefined (reading 'method')
    at Router.handle (file:///home/rags2riches-prog/artbanx/shipment-service/x-shipment-service/router.ts:11:28)
    at Object.mock.<computed> [as handle] (https://deno.land/x/rhum@v1.1.11/src/mock_builder.ts:84:24)
    at Object.testFn (file:///home/rags2riches-prog/artbanx/shipment-service/x-shipment-service/test/router.test.ts:113:46)
    at hookAttachedTestFn (https://deno.land/x/rhum@v1.1.11/src/test_case.ts:74:21)
    at https://deno.land/x/rhum@v1.1.11/src/test_case.ts:112:21
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
    at runTest (deno:runtime/js/40_testing.js:232:13)
    at Object.runTests (deno:runtime/js/40_testing.js:317:28)
```

- Notice that it isn't my guard against the method or content-type that throws
- I have tried to test the request itself (for thuthyness) in my class method but it does not change much; I still get a TypeError (this time is from my code) as if the Request object passed in the Mocked Class loses the context of the Request and does not attach the properties "method" and "content-type" to it. 

Is this the expected behaviour or is it a bug? 

I expect the test to fail but because of the characterization here:

`Rhum.asserts.assertEquals(await router.handle(req), true) // <= true should give me the output of the request as failed test`

**Comment by crookse** [comment]
@ebebbington i verified that this is a bug. your test is missing the part that surfaces the bug. you need to access `request.method` in your `handle()` method. that's when `TypeError: Cannot read properties of undefined (reading 'method')` shows up

**Comment by crookse** [comment]
@rags2riches-prog, sorry for being late on this. i have a pull request open. it includes a fix for the issue you are seeing.

**Comment by crookse** [comment]
hey @rags2riches-prog , v1.1.12 was released: https://github.com/drashland/rhum/releases/tag/v1.1.12.

it includes the fix for the issue you are seeing. you shouldn't have to change any code. it should just work, but please let me know if it doesn't. thanks for raising this issue!
