### ISSUE TITLE
Make `deno lint` pass

### ISSUE THREAD

**Issue by ebebbington** [drashland/rhum#14]
## Summary

What: If you run `deno lint`, we will most likely have a whole bunch of errors. This issue to fix these errors by correctly formatting code, and abiding by Deno's standards 

Why: It would be good to make sure the code follows either: Deno's best practices, coding standards, or general best practices. It's a Deno project so it makes sense to utilise their tools on making the code Deno-like

## Acceptance Criteria

- `deno lint` is added to the `master.yml` CI, as a new block (similar to how we use `deno fmt --check`)
- `deno lint` produces no errors

## Resources

[Deno Lint Documentation](https://github.com/denoland/deno_lint)

**Comment by Guergeiro** [comment]
Relevant: https://github.com/drashland/deno-drash/issues/264#issuecomment-647970320

**Comment by crookse** [comment]
This is being worked on by: https://github.com/littletof

**Comment by littletof** [comment]
I'm looking into this issue.

**Comment by ebebbington** [comment]
@littletof Nice one!
