### ISSUE TITLE
output in CI doesn't register unicode characters causing ugly output

### ISSUE THREAD

**Issue by crookse** [drashland/rhum#23]
<img width="1097" alt="Screen Shot 2020-06-24 at 21 47 45" src="https://user-images.githubusercontent.com/12766301/85645513-f49c6b80-b667-11ea-8b5e-d2ea77a536e7.png">

 The above screenshot is from Github Actions CI.

**Comment by Guergeiro** [comment]
Is this OS related?

**Comment by ebebbington** [comment]
> Is this OS related?

Seems like it's displaying this way for Windows,  Ubuntu and MacOS :/

**Comment by littletof** [comment]
Might this be related to: https://github.com/denoland/deno/issues/6001?

**Comment by ebebbington** [comment]
@littletof unfortunately it’s a problem with every OS in the CI :/
