### ISSUE TITLE
Video Tutorial - Stubs/Mocks

### ISSUE THREAD

**Issue by ebebbington** [drashland/rhum#36]
## Summary

What: Video tutorial (acts of visual documentation) for how to use Rhum mocks and stubs, what they are - essentially the documentation but in a video. Though it's open to whoever takes on this issue how they'd like to do the video and what content it will have.

Could be useful to include in the description of the video, times of topics, eg:

0:00 - introduction
0:23 - what are rhum stubs
5:10 - creating a. stub

Why: Supports visual learners, and thus creates another platform for people to understand Rhum stubs and mocks and how to use it - further enforcing "documentation driven"

## Information

* OBS can be used as the software to screenshare and video recording

* Includes the drashland introduction? (speak to @crookse)

* Includes the Rhum logo with the greenish background as the thumbnail

* Video can be added to a "Rhum" playlist (can also be created if it doesn't exist)

* Make it chill :)

**Comment by crookse** [comment]
closing - moving this to the private task area
