### ISSUE TITLE
Version in the README.md is causing errors with deno 1.2

### ISSUE THREAD

**Issue by ZE0TRON** [drashland/rhum#39]
**Describe the bug**
```typescript
import { Rhum } from "https://deno.land/x/rhum@v1.x/mod.ts";
```
causes std error with deno 1.2 

**Suggested Solution(s)**
```typescript
import { Rhum } from "https://deno.land/x/rhum@v1.x/mod.ts"; 
```
replace it with 
```typescript
import { Rhum } from "https://deno.land/x/rhum@v1.0.1/mod.ts"; 
```
in the README.md file

or change the automatic determined version to 1.0.1

**Comment by Guergeiro** [comment]
Hello @ZE0TRON, thank you for issue. We will try to reproduce it on our end and comeback to you as soon as possible 😄

**Comment by crookse** [comment]
@ZE0TRON, sorry about that. We forgot to merge v1.0.1 into v1.x. Could you please try the following and see if it fixes your issue:

```
deno run --reload https://deno.land/x/rhum@v1.x/mod.ts
```

**Comment by ZE0TRON** [comment]
@crookse  I have already solved it  as I mentioned above just opened this issue so that other people don't have to resolve it manually.
Thanks for quick response btw.

**Comment by crookse** [comment]
@ZE0TRON np! Closing now, v1.x branch has the latest code now.
