### ISSUE TITLE
Script to Generate Test file

### ISSUE THREAD

**Issue by ebebbington** [drashland/rhum#44]
## Summary

What: A script that would generate a test file, with the basic structure to start writing a test, using https://laravel.com/docs/7.x/dusk#generating-tests as the inspiration for this idea

Why: Think it would be a good idea, to provide some sort of CLI for Rhum?

## Acceptance Criteria

- Add acceptance criteria as bulleted list

## Example Pseudo Code (for implementation)

```typescript
// Add example pseudo code for implementation
```

**Comment by ebebbington** [comment]
What kind of syntax should we go with?

**Comment by crookse** [comment]
done: https://github.com/drashland/rhum/pull/80/commits/c5d7b69dcf515c25b82d6fd6b7e67cf3deb9349a
