### ISSUE TITLE
Rhum.only()

### ISSUE THREAD

**Issue by ebebbington** [drashland/rhum#5]
**What**

Develop the following method:

* `Rhum.only`

Method should be public and should tell Rhum to only run that test plan/suite/case **under** the parent. For example:

* If 1 suite of 2 is set to only under a plan, then the suite that doesnt have only should be skipped

**Why**
This is a testing framework dammit!

**Checklist**

* Update README where needed

* Unit & integration tests

**Resources**

Use the following [issue](https://github.com/denoland/deno/issues/4092) as a guideline if possible

**Pseudo-code for Implementation**

_All we have for information at the moment_

Needs to account for plan/suite/case, and Rhum/RhumRunner should know that there is only one to test

```typescript
Rhum.only: function (name: string, fn: Function) {
}
```

**Comment by ebebbington** [comment]
Might be easier to think of an implementation once #10 is closed, as that PR collects all tests before running them - so we could just check if any of the tests have `only` set or something then only run that test

Note though that i think it would have to apply to all tests in a suite (if the suite has `.only`)?

**Comment by crookse** [comment]
I agree. Let's wait for #10. Yea if a test suite has `.only`, then it would apply to all test cases in that suite.
