### ISSUE TITLE
Rhum.asserts has no autocompletion

### ISSUE THREAD

**Issue by rodolphocastro** [drashland/rhum#63]
## Description

When using the "shortcut" `Rhum.asserts` to build assertions we don't get intellisense support.

## To Reproduce

1. Import Rhum `v1.1.4`
2. Attempt to access auto completion for `Rhum.asserts`
3. Notice nothing relevant will show up
4. If you type the correct function name the assertion will still work as expected

## Expected behavior

I expected to get autocompletion support, the same we have for all Rhum 😅

## Suggested Solution(s)

I've been able to "export" functions with autocompletion by using a interface + a const that complied to that interface.

This is the snippet that worked for me. However those functions *are declared inside my module* so I'm not sure if this would work for mapping `Deno.test` calls.

```typescript
/**
 * Default functions for creating primitives with Dixture.
 */
export const dixtureFns: GenerationFunctions = {
  BigInt: createBigInt,
  Bool: createBoolean,
  Number: createNumber,
  String: createString,
  NamedString: <T>(prefix: keyof T) => createString(prefix.toString()),
  Int: () => createNumber(true),
  FutureDate: () => createDate(),
  PastDate: () => createDate(false),
};
```

The whole snippet can be found [here](https://github.com/rodolphocastro/dixture/blob/b53d2aa693044cdf22dbcf3f9ad10bb228f7d0cd/src/_factory.ts#L59)

The following test suites also replicate the error (as of version v1.1.4 at least): [dixture unit tests](https://github.com/rodolphocastro/dixture/tree/master/tests). _Note: I attempted to get that autocompletion to work on `deps.ts` and on the other files as well. No such luck_.

## Screenshots

The following show my attempts to get some suggestions for Rhum.asserts

![rhum asserts](https://user-images.githubusercontent.com/2666310/93726871-b80cdd00-fb8e-11ea-84a3-914722ed6dd5.gif)
![Code_1QnTwHE7Z3](https://user-images.githubusercontent.com/2666310/93726877-c0651800-fb8e-11ea-857f-4c2f6863feae.png)
![Code_Tr1GabVEKy](https://user-images.githubusercontent.com/2666310/93726882-c1964500-fb8e-11ea-9051-a582a876854e.png)
![Code_yKemxoFi3p](https://user-images.githubusercontent.com/2666310/93726884-c1964500-fb8e-11ea-94f0-9eb82f1d63c2.png)

## Desktop

- OS: Windows 10 2004
- Version `v1.1.4`
- IDE: VsCode 1.49.1 w/ Deno.Land extension
- Deno Version: 1.4.0

**Comment by rodolphocastro** [comment]
Did some digging around and found the source for `asserts`: https://github.com/drashland/rhum/blob/37b56a4e5f9dfd667711cd3a776371a3d34c89ad/src/rhum_asserts.ts#L4

My guess is this could be some issue related to exporting as a deconstruction from `deps.ts` which actually holds a full import as * from `std/asserts`?

**Comment by ebebbington** [comment]
Thanks @rodolphocastro, we'll look into it - i assume it is the way we are declaring `asserts` (or assigning the vlaues to it) because it's pulling everything from `std/testing/asserts`, and as you can see, we are doing something like:
```typescript
// deps.ts
export * as asserts from "https://deno.land/std@0.70.0/testing/asserts.ts";

// rhum.ts
import { asserts as StdAsserts } from "deps.ts"
const asserts = { ...StdAsserts };
```

Btw really good descriptive issue, the screennshots are super helpful too! :) 🎉

**Comment by rodolphocastro** [comment]
Just noticed that even inside `rhum_asserts.ts` the auto-complete goes hay-wire 😅

![image](https://user-images.githubusercontent.com/2666310/93727100-f8208f80-fb8f-11ea-948c-180ce1777873.png)

This suck as it might require some duplication to actually get it working... I've done a fork and I'll try my luck at this if you don't mind haha, worst case scenario we'd end up with some "mapping" from std/asserts and it'd require some manual updates over the time (altho I'm not sure how frequently the `asserts` over @ std would change for this to become cumbersome hahaha)

**Comment by ebebbington** [comment]
Feel free to take a dig at it :) The idea is that `Rhum.asserts` is just every assert method from std

Maybe even `asserts = StdAsserts` might provide the intellisense, but then again, i don't use vscode nor any extensions that help :P

**Comment by rodolphocastro** [comment]
No such luck with `const something = StdAsserts` as well :/

Seems that once we're relying on that import/export once we export it ourselves we lose the metadata and it just becomes any to vscode. 

Is it working as it should on your IDE? If so it could be an issue on the deno extension itself and not with Rhum haha

**Comment by ebebbington** [comment]
I get no intellisense support (i'm using PHPStorm with no plugins/extensions) :P Makes sense what you're saying - though it might be good to bring it up with the extension developers on the discord (or I can ask if you'd prefer), because it might be an extension issue? Regardless the issue can still be worked on

**Comment by rodolphocastro** [comment]
If you could bring it up I'd appreciate it! It's almost 11pm and I'm about to head off to sleep haha.

Did a last shot at the destructuring approach and nada yet
![image](https://user-images.githubusercontent.com/2666310/93727734-e096d600-fb92-11ea-9754-e7e1611ed41c.png)
![image](https://user-images.githubusercontent.com/2666310/93727744-f6a49680-fb92-11ea-99c4-bb3366717a6c.png)
![image](https://user-images.githubusercontent.com/2666310/93727759-07eda300-fb93-11ea-9327-cc34ba35b2b3.png)

I'm against code duplication but if this ends up not being an issue on the extension itself it might be worth, from a module consumer's point of view, to have that autocompletion even if it means some manual mapping...  What do you think?

**Comment by ebebbington** [comment]
Yeah alright i'll have to give it a try tomorrow though (3am atm), but it's not ideal but **i'm not against it**, will see what @Guergeiro @crookse @saragee3 think

**Comment by rodolphocastro** [comment]
@ebebbington Actually the change might be needed just on the `mod.ts` itself

Just noticed that the `asserts` get a new typing once they get up to `mod.ts` and after removing that typing and allowing ts to infer it things worked like a charm 🎊

![image](https://user-images.githubusercontent.com/2666310/93728038-7717c700-fb94-11ea-9f5b-538288f52931.png)
![image](https://user-images.githubusercontent.com/2666310/93728044-7ed76b80-fb94-11ea-9369-d60741c5e072.png)

(_Note: this does make 2 integration tests fail so it's def. not final hahah_)

I'll commit my changes as WIP on the fork for now. Maybe applying a public-only interface to `RhumRunner.asserts` that maps the "official" asserts would be enough 💡

Commit with changes so far: https://github.com/rodolphocastro/rhum/commit/f23b8c9c9735e40c643bfc62f466f0852a663e0f

**Comment by rodolphocastro** [comment]
I might have a solution!

Using an extra type that looks into `assert` keys + some changes to the existing typing that was in-use before my commit:

![image](https://user-images.githubusercontent.com/2666310/93728588-f73f2c00-fb96-11ea-9abc-11a97d1e27fa.png)
![image](https://user-images.githubusercontent.com/2666310/93728598-ff976700-fb96-11ea-87c5-ce73f0e184fc.png)

As a bonus this one doesn't break any of the integration tests 👍 
https://github.com/rodolphocastro/rhum/commit/a794bd040b324f709bc10d8ccb289e6204577f03

**Comment by ebebbington** [comment]
@rodolphocastro looking into it now

**Comment by ebebbington** [comment]
@rodolphocastro come to the discord as it might be easier: https://discord.gg/NMe97z

i'm not even getting any intellisense after typing `Rhum` :S

**Comment by ebebbington** [comment]
Cracked the badger

**Comment by ebebbington** [comment]
![Uploading image.png…]()

**Comment by rodolphocastro** [comment]
Sweet! If you still need I'll be able to hop into discord in a few hours but seems everything is golden now 💪

**Comment by ebebbington** [comment]
Seems like it, and you can be the one to mark sure it works when we release ;) My PR pretty much just used what you have done in this issue, so most credit goes to you 👍

**Comment by rodolphocastro** [comment]
Me neither hahah. That idea came to me as I was getting ready to sleep and I thought "what if we used the `keyof` function?". Then I quickly turned on my laptop and took that shot from the previous comment 😂

Once that gets published I'll be sure to come by and mark this as working 🥳
